name: Docker Image Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm32v7, arm64v8]
        version: ["1.15.8.3", "1.17.8.1rc1"]
    steps:
    - uses: actions/checkout@v1
    - name: Get qemu-user-static
      run: sudo apt-get update && sudo apt-get install -y qemu-user-static
    - name: Configure Docker
      run: |
        echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker run --rm --privileged multiarch/qemu-user-static:register
    - name: Build the Docker image
      run: |
        if [[ "$ARCH" == "amd64" ]]; then export QEMU_BIN="qemu-x86_64-static"; fi
        if [[ "$ARCH" == "arm32v7" ]]; then export QEMU_BIN="qemu-arm-static"; fi
        if [[ "$ARCH" == "arm64v8" ]]; then export QEMU_BIN="qemu-aarch64-static"; fi
        cp /usr/bin/$QEMU_BIN ./
        docker build . --build-arg="ARCH=$ARCH" --build-arg="OPENRESTY_VERSION=$VERSION" --build-arg="QEMU_BIN=$QEMU_BIN" --file Dockerfile --tag $DOCKER_PREFIX:$ARCH-$VERSION
      env:
        ARCH: ${{ matrix.arch }}
        VERSION: ${{ matrix.version }}
        DOCKER_CLI_EXPERIMENTAL: enabled
        DOCKER_PREFIX: maartje/openresty
    - name: Log in to registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "meyskens" --password-stdin
    - name: Push image
      run: docker push maartje/openresty
  publish-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        version: ["1.15.8.3", "1.17.8.1rc1"]
    steps:
      - name: Configure Docker
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "meyskens" --password-stdin
      - name: Create Manifest 
        run: |
          docker manifest create $DOCKER_PREFIX:$VERSION $DOCKER_PREFIX:amd64-$VERSION $DOCKER_PREFIX:arm32v7-$VERSION $DOCKER_PREFIX:arm64v8-$VERSION
          docker manifest annotate $DOCKER_PREFIX:$VERSION  $DOCKER_PREFIX:amd64-$VERSION --arch amd64
          docker manifest annotate $DOCKER_PREFIX:$VERSION  $DOCKER_PREFIX:arm32v7-$VERSION --arch arm --variant v7
          docker manifest annotate $DOCKER_PREFIX:$VERSION  $DOCKER_PREFIX:arm64v8-$VERSION --arch arm64 --variant armv8
          docker manifest push $DOCKER_PREFIX:$VERSION
        env:
          VERSION: ${{ matrix.version }}
          DOCKER_PREFIX: maartje/openresty
          DOCKER_CLI_EXPERIMENTAL: enabled
